spring:
  application:
    name: taskify

  graphql:
    path: /graphql
    graphiql.enabled: true

  jackson:
    time-zone: America/Sao_Paulo

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: taskify
    password: yS510d1OM

  jpa:
    properties:
      hibernate:
        default_schema: public

logging:
  level:
    org:
      springframework:
        web: INFO

br.com.mulero.taskify:
  security:
    jwtSecret: ${JWT_SECRET:Xv?ZZGF8*x_?X29R}