spring:
  application:
    name: taskify

  graphql:
    path: /graphql
    graphiql.enabled: true

  jackson:
    time-zone: America/Sao_Paulo

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: taskify
    password: yS510d1OM

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  security:
    secret: "Xv?ZZGF8*x_?X29R"

logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
        data: INFO
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE